### ISSUE TITLE
ImportError: cannot import name softmax

### ISSUE THREAD

**Issue by aj-ptw** [alexandrebarachant/pyRiemann#39]
Trying to import:

```python
from pyriemann.clustering import potato
```

and run with 
```
$ python foo.py
```

Running into this error:
```
$ python python/handoff.py

Traceback (most recent call last):
  File "python/handoff.py", line 2, in <module>
    from pyriemann.clustering import potato
  File "/Users/ajk/anaconda/lib/python2.7/site-packages/pyriemann-0.2.4-py2.7.egg/pyriemann/__init__.py", line 1, in <module>
    from . import classification
  File "/Users/ajk/anaconda/lib/python2.7/site-packages/pyriemann-0.2.4-py2.7.egg/pyriemann/classification.py", line 7, in <module>
    from sklearn.utils.extmath import softmax
ImportError: cannot import name softmax
```

I am running 2.7
```
$ python --version
Python 2.7.11 :: Anaconda 2.3.0 (x86_64)
```

**Comment by alexandrebarachant** [comment]
Hi,
your version of scikit learn is probably too old. which version did you use ?

**Comment by aj-ptw** [comment]
The most recent. I used pip

**Comment by alexandrebarachant** [comment]
the last source code version do contain `softmax`
https://github.com/scikit-learn/scikit-learn/blob/master/sklearn/utils/extmath.py#L699

try a `pip install scikit-learn --updgrde`

**Comment by aj-ptw** [comment]
Yea I'm on the current and I checked to make sure i couldn't upgrade:

```
$ pip show scikit-learn
---
Metadata-Version: 1.1
Name: scikit-learn
Version: 0.17.1
Summary: A set of python modules for machine learning and data mining
Home-page: http://scikit-learn.org
Author: Andreas Mueller

Author-email: amueller@ais.uni-bonn.de
License: new BSD
Location: /anaconda/lib/python2.7/site-packages
Requires:
Classifiers:
  Intended Audience :: Science/Research
  Intended Audience :: Developers
  License :: OSI Approved
  Programming Language :: C
  Programming Language :: Python
  Topic :: Software Development
  Topic :: Scientific/Engineering
  Operating System :: Microsoft :: Windows
  Operating System :: POSIX
  Operating System :: Unix
  Operating System :: MacOS
  Programming Language :: Python :: 2
  Programming Language :: Python :: 2.6
  Programming Language :: Python :: 2.7
  Programming Language :: Python :: 3
  Programming Language :: Python :: 3.3
  Programming Language :: Python :: 3.4
 Andrews-Air /Users/andrewkeller/Thinker python
$ pip install scikit-learn --upgrade
Requirement already up-to-date: scikit-learn in /anaconda/lib/python2.7/site-packages
```

**Comment by aj-ptw** [comment]
Hey it seems that my other computer must not be up to date on `scikit-learn`. Computer running `0.17.1` is working. my apologies!
