### ISSUE TITLE
couple of tests are failing under python3

### ISSUE THREAD

**Issue by ignatenkobrain** [alexandrebarachant/pyRiemann#51]
```python
======================================================================
ERROR: Test transform of channelselection.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/brain/Projects/fedora/python-pyriemann/pyRiemann-0.2.4/tests/test_channelselection.py", line 20, in test_ElectrodeSelection_transform
    se.fit(covset, labels)
  File "/home/brain/rpmbuild/BUILDROOT/python-pyriemann-0.2.4-1.fc27.x86_64/usr/lib/python3.6/site-packages/pyriemann/channelselection.py", line 93, in fit
    sub.pop(idx)
AttributeError: 'range' object has no attribute 'pop'

======================================================================
ERROR: Test Fit of FgMDM
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/brain/Projects/fedora/python-pyriemann/pyRiemann-0.2.4/tests/test_classification.py", line 67, in test_FgMDM_fit
    mdm.fit(covset,labels)
  File "/home/brain/rpmbuild/BUILDROOT/python-pyriemann-0.2.4-1.fc27.x86_64/usr/lib/python3.6/site-packages/pyriemann/classification.py", line 283, in fit
    cov = self._fgda.fit_transform(X, y)
  File "/home/brain/rpmbuild/BUILDROOT/python-pyriemann-0.2.4-1.fc27.x86_64/usr/lib/python3.6/site-packages/pyriemann/tangentspace.py", line 308, in fit_transform
    ts = self._fit_lda(X, y, sample_weight=sample_weight)
  File "/home/brain/rpmbuild/BUILDROOT/python-pyriemann-0.2.4-1.fc27.x86_64/usr/lib/python3.6/site-packages/pyriemann/tangentspace.py", line 240, in _fit_lda
    ts = self._ts.fit_transform(X, sample_weight=sample_weight)
  File "/home/brain/rpmbuild/BUILDROOT/python-pyriemann-0.2.4-1.fc27.x86_64/usr/lib/python3.6/site-packages/pyriemann/tangentspace.py", line 169, in fit_transform
    return tangent_space(X, self.reference_)
  File "/home/brain/rpmbuild/BUILDROOT/python-pyriemann-0.2.4-1.fc27.x86_64/usr/lib/python3.6/site-packages/pyriemann/utils/tangentspace.py", line 20, in tangent_space
    T = numpy.empty((Nt, Ne * (Ne + 1) / 2))
TypeError: 'float' object cannot be interpreted as an integer

======================================================================
ERROR: Test prediction of FgMDM
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/brain/Projects/fedora/python-pyriemann/pyRiemann-0.2.4/tests/test_classification.py", line 74, in test_FgMDM_predict
    mdm.fit(covset,labels)
  File "/home/brain/rpmbuild/BUILDROOT/python-pyriemann-0.2.4-1.fc27.x86_64/usr/lib/python3.6/site-packages/pyriemann/classification.py", line 283, in fit
    cov = self._fgda.fit_transform(X, y)
  File "/home/brain/rpmbuild/BUILDROOT/python-pyriemann-0.2.4-1.fc27.x86_64/usr/lib/python3.6/site-packages/pyriemann/tangentspace.py", line 308, in fit_transform
    ts = self._fit_lda(X, y, sample_weight=sample_weight)
  File "/home/brain/rpmbuild/BUILDROOT/python-pyriemann-0.2.4-1.fc27.x86_64/usr/lib/python3.6/site-packages/pyriemann/tangentspace.py", line 240, in _fit_lda
    ts = self._ts.fit_transform(X, sample_weight=sample_weight)
  File "/home/brain/rpmbuild/BUILDROOT/python-pyriemann-0.2.4-1.fc27.x86_64/usr/lib/python3.6/site-packages/pyriemann/tangentspace.py", line 169, in fit_transform
    return tangent_space(X, self.reference_)
  File "/home/brain/rpmbuild/BUILDROOT/python-pyriemann-0.2.4-1.fc27.x86_64/usr/lib/python3.6/site-packages/pyriemann/utils/tangentspace.py", line 20, in tangent_space
    T = numpy.empty((Nt, Ne * (Ne + 1) / 2))
TypeError: 'float' object cannot be interpreted as an integer

======================================================================
ERROR: Test fit CospCovariances
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/brain/Projects/fedora/python-pyriemann/pyRiemann-0.2.4/tests/test_estimation.py", line 47, in test_Cospcovariances
    cov.fit_transform(x)
  File "/home/brain/rpmbuild/BUILDROOT/python-pyriemann-0.2.4-1.fc27.x86_64/usr/lib/python3.6/site-packages/pyriemann/estimation.py", line 270, in fit_transform
    return self.transform(X)
  File "/home/brain/rpmbuild/BUILDROOT/python-pyriemann-0.2.4-1.fc27.x86_64/usr/lib/python3.6/site-packages/pyriemann/estimation.py", line 264, in transform
    fmin=self.fmin, fmax=self.fmax, fs=self.fs)
  File "/home/brain/rpmbuild/BUILDROOT/python-pyriemann-0.2.4-1.fc27.x86_64/usr/lib/python3.6/site-packages/pyriemann/utils/covariance.py", line 123, in cospectrum
    fdata = numpy.zeros((number_windows, Ne, number_freqs), dtype=complex)
TypeError: 'float' object cannot be interpreted as an integer

======================================================================
ERROR: Test one way permutation test
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/brain/Projects/fedora/python-pyriemann/pyRiemann-0.2.4/tests/test_stats.py", line 18, in test_permutation_test
    p.test(covset,labels)
  File "/home/brain/rpmbuild/BUILDROOT/python-pyriemann-0.2.4-1.fc27.x86_64/usr/lib/python3.6/site-packages/pyriemann/stats.py", line 186, in test
    self.F_ = numpy.zeros(numpy.min([self.n_perms, Npe]))
TypeError: 'numpy.float64' object cannot be interpreted as an integer

======================================================================
ERROR: Test transform of Tangent Space.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/brain/Projects/fedora/python-pyriemann/pyRiemann-0.2.4/tests/test_tangentspace.py", line 34, in test_TangentSpace_transform
    ts.transform(covset)
  File "/home/brain/rpmbuild/BUILDROOT/python-pyriemann-0.2.4-1.fc27.x86_64/usr/lib/python3.6/site-packages/pyriemann/tangentspace.py", line 146, in transform
    return tangent_space(X, Cr)
  File "/home/brain/rpmbuild/BUILDROOT/python-pyriemann-0.2.4-1.fc27.x86_64/usr/lib/python3.6/site-packages/pyriemann/utils/tangentspace.py", line 20, in tangent_space
    T = numpy.empty((Nt, Ne * (Ne + 1) / 2))
TypeError: 'float' object cannot be interpreted as an integer

======================================================================
ERROR: Test transform of Tangent Space without fit.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/brain/Projects/fedora/python-pyriemann/pyRiemann-0.2.4/tests/test_tangentspace.py", line 41, in test_TangentSpace_transform_without_fit
    ts.transform(covset)
  File "/home/brain/rpmbuild/BUILDROOT/python-pyriemann-0.2.4-1.fc27.x86_64/usr/lib/python3.6/site-packages/pyriemann/tangentspace.py", line 146, in transform
    return tangent_space(X, Cr)
  File "/home/brain/rpmbuild/BUILDROOT/python-pyriemann-0.2.4-1.fc27.x86_64/usr/lib/python3.6/site-packages/pyriemann/utils/tangentspace.py", line 20, in tangent_space
    T = numpy.empty((Nt, Ne * (Ne + 1) / 2))
TypeError: 'float' object cannot be interpreted as an integer

======================================================================
ERROR: Test transform of Tangent Space with TSupdate.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/brain/Projects/fedora/python-pyriemann/pyRiemann-0.2.4/tests/test_tangentspace.py", line 49, in test_TangentSpace_transform_with_ts_update
    ts.transform(covset)
  File "/home/brain/rpmbuild/BUILDROOT/python-pyriemann-0.2.4-1.fc27.x86_64/usr/lib/python3.6/site-packages/pyriemann/tangentspace.py", line 146, in transform
    return tangent_space(X, Cr)
  File "/home/brain/rpmbuild/BUILDROOT/python-pyriemann-0.2.4-1.fc27.x86_64/usr/lib/python3.6/site-packages/pyriemann/utils/tangentspace.py", line 20, in tangent_space
    T = numpy.empty((Nt, Ne * (Ne + 1) / 2))
TypeError: 'float' object cannot be interpreted as an integer

======================================================================
ERROR: Test inverse transform of Tangent Space.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/brain/Projects/fedora/python-pyriemann/pyRiemann-0.2.4/tests/test_tangentspace.py", line 57, in test_TangentSpace_inversetransform
    t = ts.transform(covset)
  File "/home/brain/rpmbuild/BUILDROOT/python-pyriemann-0.2.4-1.fc27.x86_64/usr/lib/python3.6/site-packages/pyriemann/tangentspace.py", line 146, in transform
    return tangent_space(X, Cr)
  File "/home/brain/rpmbuild/BUILDROOT/python-pyriemann-0.2.4-1.fc27.x86_64/usr/lib/python3.6/site-packages/pyriemann/utils/tangentspace.py", line 20, in tangent_space
    T = numpy.empty((Nt, Ne * (Ne + 1) / 2))
TypeError: 'float' object cannot be interpreted as an integer

======================================================================
ERROR: Test inverse transform of Tangent Space without fit.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/brain/Projects/fedora/python-pyriemann/pyRiemann-0.2.4/tests/test_tangentspace.py", line 66, in test_TangentSpace_inversetransform_without_fit
    tsv = np.random.randn(Nt, Ne)
  File "mtrand.pyx", line 1404, in mtrand.RandomState.randn (numpy/random/mtrand/mtrand.c:19843)
  File "mtrand.pyx", line 1534, in mtrand.RandomState.standard_normal (numpy/random/mtrand/mtrand.c:20368)
  File "mtrand.pyx", line 167, in mtrand.cont0_array (numpy/random/mtrand/mtrand.c:6127)
TypeError: 'float' object cannot be interpreted as an integer

======================================================================
ERROR: Test Fit of FGDA.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/brain/Projects/fedora/python-pyriemann/pyRiemann-0.2.4/tests/test_tangentspace.py", line 81, in test_FGDA_fit
    ts.fit(covset, labels)
  File "/home/brain/rpmbuild/BUILDROOT/python-pyriemann-0.2.4-1.fc27.x86_64/usr/lib/python3.6/site-packages/pyriemann/tangentspace.py", line 271, in fit
    self._fit_lda(X, y, sample_weight=sample_weight)
  File "/home/brain/rpmbuild/BUILDROOT/python-pyriemann-0.2.4-1.fc27.x86_64/usr/lib/python3.6/site-packages/pyriemann/tangentspace.py", line 240, in _fit_lda
    ts = self._ts.fit_transform(X, sample_weight=sample_weight)
  File "/home/brain/rpmbuild/BUILDROOT/python-pyriemann-0.2.4-1.fc27.x86_64/usr/lib/python3.6/site-packages/pyriemann/tangentspace.py", line 169, in fit_transform
    return tangent_space(X, self.reference_)
  File "/home/brain/rpmbuild/BUILDROOT/python-pyriemann-0.2.4-1.fc27.x86_64/usr/lib/python3.6/site-packages/pyriemann/utils/tangentspace.py", line 20, in tangent_space
    T = numpy.empty((Nt, Ne * (Ne + 1) / 2))
TypeError: 'float' object cannot be interpreted as an integer

======================================================================
ERROR: Test transform of FGDA.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/brain/Projects/fedora/python-pyriemann/pyRiemann-0.2.4/tests/test_tangentspace.py", line 89, in test_FGDA_transform
    ts.fit(covset, labels)
  File "/home/brain/rpmbuild/BUILDROOT/python-pyriemann-0.2.4-1.fc27.x86_64/usr/lib/python3.6/site-packages/pyriemann/tangentspace.py", line 271, in fit
    self._fit_lda(X, y, sample_weight=sample_weight)
  File "/home/brain/rpmbuild/BUILDROOT/python-pyriemann-0.2.4-1.fc27.x86_64/usr/lib/python3.6/site-packages/pyriemann/tangentspace.py", line 240, in _fit_lda
    ts = self._ts.fit_transform(X, sample_weight=sample_weight)
  File "/home/brain/rpmbuild/BUILDROOT/python-pyriemann-0.2.4-1.fc27.x86_64/usr/lib/python3.6/site-packages/pyriemann/tangentspace.py", line 169, in fit_transform
    return tangent_space(X, self.reference_)
  File "/home/brain/rpmbuild/BUILDROOT/python-pyriemann-0.2.4-1.fc27.x86_64/usr/lib/python3.6/site-packages/pyriemann/utils/tangentspace.py", line 20, in tangent_space
    T = numpy.empty((Nt, Ne * (Ne + 1) / 2))
TypeError: 'float' object cannot be interpreted as an integer

======================================================================
ERROR: Test eegtocov
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/brain/Projects/fedora/python-pyriemann/pyRiemann-0.2.4/tests/test_utils_covariance.py", line 40, in test_covariances_cospectrum
    cov = cospectrum(x)
  File "/home/brain/rpmbuild/BUILDROOT/python-pyriemann-0.2.4-1.fc27.x86_64/usr/lib/python3.6/site-packages/pyriemann/utils/covariance.py", line 123, in cospectrum
    fdata = numpy.zeros((number_windows, Ne, number_freqs), dtype=complex)
TypeError: 'float' object cannot be interpreted as an integer

======================================================================
ERROR: Test tangent space projection
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/brain/Projects/fedora/python-pyriemann/pyRiemann-0.2.4/tests/test_utils_tangent_space.py", line 18, in test_tangent_space
    T = tangent_space(C,np.eye(3))
  File "/home/brain/rpmbuild/BUILDROOT/python-pyriemann-0.2.4-1.fc27.x86_64/usr/lib/python3.6/site-packages/pyriemann/utils/tangentspace.py", line 20, in tangent_space
    T = numpy.empty((Nt, Ne * (Ne + 1) / 2))
TypeError: 'float' object cannot be interpreted as an integer

======================================================================
ERROR: Test tangent space projection and retro-projection should be the same
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/brain/Projects/fedora/python-pyriemann/pyRiemann-0.2.4/tests/test_utils_tangent_space.py", line 28, in test_tangent_and_untangent_space
    T = tangent_space(C,np.eye(3))
  File "/home/brain/rpmbuild/BUILDROOT/python-pyriemann-0.2.4-1.fc27.x86_64/usr/lib/python3.6/site-packages/pyriemann/utils/tangentspace.py", line 20, in tangent_space
    T = numpy.empty((Nt, Ne * (Ne + 1) / 2))
TypeError: 'float' object cannot be interpreted as an integer
```

**Comment by alexandrebarachant** [comment]
interesting. 
Is this the current master branch ?

it's working for python 3.5, i will add python 3.6 in travis

**Comment by ignatenkobrain** [comment]
@alexandrebarachant no, it's latest release. I didn't check master though..

**Comment by alexandrebarachant** [comment]
okay. i actually fixed those issues not so long ago.
Use the current version from the master branch, and you are good to go.

I will package a new release soon.

**Comment by alexandrebarachant** [comment]
I'm closing this issue.
